---
common:
  paymentsApiToken: TestToken

antaeus:
  image:
    repository: "dfroberg/pleo-antaeus"
    tag: "latest"
    pullPolicy: "Always"
  env:
    - name: "TZ"
      value: "Europe/Stockholm"
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    ingressClassName: "traefik"
    domain:
      base: "antaeus.local"
      prefix: ""
      suffix: ""
  testService:
    enabled: true
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 4096Mi

payment:
  image:
    repository: "dfroberg/pleo-payment"
    tag: "latest"
    pullPolicy: "Always"
  env:
    - name: "TZ"
      value: "Europe/Stockholm"
  networkPolicy:
    enabled: true
  resources:
    limits:
      memory: "64Mi"
      cpu: "250m"
