kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: payments
spec:
  podSelector:
    matchLabels: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-everyone-access-to-antaeus
  namespace: payments
  labels:
    app: antaeus 
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: antaeus
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-antaeus-access-to-payments
  namespace: payments
  labels:
    app: antaeus 
spec:
  podSelector:
    matchLabels:
      app: payments
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: antaeus
    ports:
    - protocol: TCP
      port: 9000
