---
apiVersion: v2
name: antaeus
type: application
version: 0.1.14
appVersion: v0.1.0
description: |
  Antaeus helm chart is the solution for the Pleo SRE challenge and
  contains a microservice with an payment provider.
  ---
  How to get it;
  ~~~
  helm repo add antaeus https://dfroberg.github.io/tinjis/
  helm repo update
  ~~~
  Take a look;
  ~~~
  helm search repo antaeus
  ~~~
  How to install it;
  ~~~
  helm upgrade antaeus antaeus/antaeus \
        --install \
        --namespace payments \
        --create-namespace \
        --wait \
        --set antaeus.image.tag=latest \
        --set antaeus.ingress.enabled=true \
        --set antaeus.ingress.domain.prefix="" \
        --set antaeus.ingress.domain.base=antaeus.local \
        --set antaeus.testService.enabled=true \
        --set payment.networkPolicy.enabled=true
  ~~~

home: https://github.com/dfroberg/tinjis
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
sources:
- https://github.com/dfroberg/tinjis/tree/master/antaeus
maintainers:
  - name: dfroberg
    email: danny@froberg.org

