---
apiVersion: v2
name: antaeus
description: |
  Antaeus helm chart is the solution for the Pleo SRE challenge and 
  contains a microservice with an payment provider.
  
  How to get it;
  ~~~
  helm repo add antaeus https://dfroberg.github.io/tinjis/
  helm repo update
  ~~~
  Take a look;
  ~~~
  helm search repo antaeus
  ~~~
  How to install it;
  ~~~
  helm upgrade antaeus antaeus \
        --install \
        --namespace test-antaeus \
        --create-namespace \
        --wait \
        --set antaeus.image.tag=latest \
        --set antaeus.ingress.enabled=true \
        --set antaeus.ingress.domain.prefix=test \
        --set antaeus.ingress.domain.base=antaeus.local \
        --set antaeus.testService.enabled=true \
        --set payment.networkPolicy.enabled=true \

  ~~~

home: https://github.com/dfroberg/tinjis
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
sources:
- https://github.com/dfroberg/tinjis/charts/antaeus
maintainers:
  - name: dfroberg
    email: danny@froberg.org
type: application

# This is the chart version. This version number should be incremented each time
# you make changes to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version
# number should be incremented each time you make changes to the application.
# Versions are not expected to follow Semantic Versioning. They should reflect
# the version the application is using.
appVersion: v0.1.0
