---
# -- Common values for all services
common:
  # -- This is optional, will be pupulated by a random string if not defined or already present in a secret.
  paymentsApiToken: TestToken

# -- Values for antaeus service
antaeus:
  image:
    repository: "dfroberg/pleo-antaeus"
    tag: "latest"
    pullPolicy: "Always"
  # -- Environment vars to set
  env:
    TZ: "Europe/Stockholm"
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    #  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    ingressClassName: "traefik"
    domain:
      base: "antaeus.local"
      prefix: ""
      suffix: ""
  testService:
    # -- Enable if you wish to deploy a NodePort test service
    enabled: true
  # -- Resource limits
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 1024m
      memory: 4096Mi

# -- Values for payment service
payment:
  image:
    repository: "dfroberg/pleo-payment"
    tag: "latest"
    pullPolicy: "Always"
  # -- Environment vars to set
  env:
    TZ: "Europe/Stockholm"
  networkPolicy:
    # -- Allow communication to this service ONLY from antaeus
    enabled: true
  # -- Resource limits
  resources:
    limits:
      memory: "64Mi"
      cpu: "250m"
