---
# -- Common values for all services
common:
  # -- This is optional, will be pupulated by a random string if not defined or already present in a secret.
  paymentsApiToken: TestToken

# -- Values for antaeus service
antaeus:
  image:
    repository: "dfroberg/pleo-antaeus"
    tag: "latest"
    pullPolicy: "Always"
  # -- Environment vars to set
  env:
    - name: "TZ"
      value: "Europe/Stockholm"
  ingress:
    # -- Enable ingress
    enabled: true
    # -- Ingress annotations
    annotations: {}
    # -- Ingress labels
    labels: {}
    #  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # -- IngressClassname
    ingressClassName: "traefik"
    # -- Build host string
    domain:
      base: "antaeus.local"
      prefix: ""
      suffix: ""
  # Antaeus service
  service:
    # -- Port number (Defaults to 8000)
    port: 8000
  testService:
    # -- Enable if you wish to deploy a NodePort test service
    enabled: true
    # -- Port number (Defaults to 8000)
    port: 8000
  # -- Resource limits
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 1024m
      memory: 4096Mi

# -- Values for payment service
payment:
  image:
    repository: "dfroberg/pleo-payment"
    tag: "latest"
    pullPolicy: "Always"
  # -- Environment vars to set
  env:
    - name: "TZ"
      value: "Europe/Stockholm"
  # Payment service
  service:
    # -- Port number (Defaults to 9000)
    port: 9000
  networkPolicy:
    # -- Allow communication to this service ONLY from antaeus
    enabled: true
  # -- Resource limits
  resources:
    limits:
      memory: "64Mi"
      cpu: "250m"
