---
{{- if (.Values.antaeus.testService.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: antaeus-test-service
  namespace: payments
  labels:
    app: antaeus
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: NodePort
  ports:
    - port: {{- .Values.antaeus.testService.port | default 8000 }}
      protocol: TCP
  selector:
    app: antaeus
{{ end }}
