---
apiVersion: v1
kind: Service
metadata:
  name: antaeus-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: antaeus
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app: antaeus
