---
{{- if (.Values.antaeus.ingress.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: antaeus-ingress
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: antaeus
    {{- with .Values.antaeus.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    {{- with .Values.antaeus.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.antaeus.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.antaeus.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: antaeus-service
                port:
                  number: 8000
{{- end -}}
