---
apiVersion: v1
kind: Secret
metadata:
  name: common-payments-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  PAYMENTS_API_TOKEN: {{ include "common.payments-api-token" . | b64enc }}
