---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Release.Namespace }}"
  labels:
    app: antaeus
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec: {}
status: {}
