---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: payments
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.payment.service.port | default 9000 }}
      protocol: TCP
  selector:
    app: payments
