---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: payments
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: payments
  replicas: 1
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: "{{ .Values.payment.image.repository | default "dfroberg/pleo-payment" }}:{{ .Values.payment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.payment.image.pullPolicy | default "IfNotPresent" }}  
          resources:
            {{- toYaml .Values.payment.resources | nindent 10 }}
          ports:
            - containerPort: 9000
          env:
            - name: PAYMENTS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-payments-secret
                  key: PAYMENTS_API_TOKEN
          {{- with .Values.payment.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
