name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push pleo-antaeus
        uses: docker/build-push-action@v2
        with:
          context: antaeus
          push: true
          tags: dfroberg/pleo-antaeus:latest
      - name: Build and push pleo-payment
        uses: docker/build-push-action@v2
        with:
          context: payment
          push: true
          tags: dfroberg/pleo-payment:latest
