---
name: 'Helm Deploy Pull Request'
on:
  pull_request:
    types: [labeled]

jobs:
  deploy-pr:
    name: 'Deploy Pull Request'
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'deploy' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push pleo-antaeus
      uses: docker/build-push-action@v2
      with:
        context: antaeus
        push: true
        tags: dfroberg/pleo-antaeus::pr-${{ github.event.pull_request.number }}
    - name: Build and push pleo-payment
      uses: docker/build-push-action@v2
      with:
        context: payment
        push: true
        tags: dfroberg/pleo-payment::pr-${{ github.event.pull_request.number }}

    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    - name: Install helm
      run: |
        curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
        tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
        helm version

    - name: Lint helm charts
      run: helm lint ./charts/antaeus/

    - name: Install Helm Chart
      working-directory: env/helm
      run: |
        helm upgrade pr-${{ github.event.pull_request.number }} antaeus/antaeus \
          --install \
          --namespace pr-${{ github.event.pull_request.number }} \
          --create-namespace \
          --wait \
          --set antaeus.image.tag=pr-${{ github.event.pull_request.number }} \
          --set antaeus.testService.enabled=true
          --set antaeus.ingress.ingressClassName="traefik" \
          --set antaeus.ingress.domain.base=${{ secrets.HELM_DOMAIN }} \
          --set antaeus.ingress.domain.prefix=pr-${{ github.event.pull_request.number }}.pr \
          --set payment.image.tag=pr-${{ github.event.pull_request.number }} \
          --set payment.image.networkPolicy.enabled=true
    - name: Install Helm Chart
      working-directory: env/helm
      run: |
        helm test pr-${{ github.event.pull_request.number }}
    - name: Post comment to Pull Request
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Your Pull Request Deployment is ready for review at https://pr-${{ github.event.pull_request.number }}.pr.${{ secrets.HELM_DOMAIN }}"
        check_for_duplicate_msg: true