name: Kuberenetes Matrix Testing
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci", "Manifest Validation"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v1.22.8-k3s1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: ${{ matrix.k8s_version }}
      - name: Test on k3s
        run: |
          # Check cluster
          kubectl get nodes -owide
          # Check and deploy
          ./k8s-check.sh
          ./k8s-deploy.sh
          kubectl apply -f manifests/antaeus-ingress.yaml
          kubectl apply -f manifests/antaeus-test-service.yaml
          # Make test domain resolvable
          export IPA=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
          echo "$IPA antaeus.local" | sudo tee -a /etc/hosts
          # Run Tests
          ./k8s-test.sh


