name: Matrix Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [latest,v1.21.2-k3s1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: ${{ matrix.k8s_version }}
      - name: Test on k3s
        run: |
          kubectl get nodes -owide
          ./k8s-check.sh
          sleep 60
          ./k8s-deploy.sh
          kubectl apply -f manifests/antaeus-ingress.yaml
          # Deploy Test SVC
          echo "172.17.0.2 antaeus.local" | sudo tee -a /etc/hosts 
          cat /etc/hosts
          host antaeus.local
          ip r
          # kubectl apply -f manifests/antaeus-test-service.yaml
          # Run Tests
          kubectl get all -n payments 
          kubectl get ing -n payments 
          ./k8s-test.sh


