name: Matrix Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v1.21.2-k3s1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: ${{ matrix.k8s_version }}
      - name: Test on k3s
        run: |
          kubectl get nodes -owide
          ./k8s-check.sh
          ./k8s-deploy.sh
          kubectl apply -f manifests/antaeus-ingress.yaml
          # Deploy Test SVC
          IPA=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
          kubectl get ing -n payments -oyaml antaeus-ingress
          sleep 60
          kubectl get ing -n payments -oyaml antaeus-ingress
          echo "$IPA antaeus.local" | sudo tee -a /etc/hosts 
          cat /etc/hosts
          ip a
          ip r
          netstat -plant
          curl -I -s http://antaeus.local/rest/health && true
          curl -I -s -H "Host: antaeus.local" http://127.0.0.1/rest/health && true
          # kubectl apply -f manifests/antaeus-test-service.yaml
          # Run Tests
          kubectl get all -n payments 
          kubectl get ing -n payments 
          ./k8s-test.sh


