name: Lint and Test antaeus Chart

on:
  pull_request:
    branches:
      - master
    paths:
      - 'charts/antaeus/values.yaml'
      - 'charts/antaeus/Chart.yaml'
      - 'charts/antaeus/templates/**.yaml'

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (lint)
        run: helm lint ./charts/antaeus/

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Run chart-testing (install)
        run: ct install --charts ./charts/antaeus