name: Manifest Validation

on:
  pull_request:
  push:
    branches:
      - 'master'
    paths:
      - 'manifests/**/*'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in manifests
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.1
        with:
          files: manifests
          token: ${{ secrets.GITHUB_TOKEN }}
