name: Update docs

on:
  push:
    branches:
      - master
    paths:
      - 'public/**'
      - 'charts/*/templates/**'
      - 'charts/*/values.yaml'
      - 'charts/*/Chart.yaml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run helm-docs
        run: |
          GOBIN=$PWD GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs
          ./helm-docs --sort-values-order file
          rm helm-docs

      - name: Commit bump
        uses: EndBug/add-and-commit@v7
        with:
            branch: ${{ github.event.pull_request.base.ref }}
            message: 'Regenerate chart README.md'
      - name: Deploy README
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
          keep_files: true